[package]
name = "mathf"
version = "0.1.13"
authors = ["Julia Naomi <jnboeira@outlook.com>"]
description = "Math crate for Godi Game Engine"
repository = "https://github.com/GodiStudios/mathf"
keywords = ["Vectorial", "Game", "Mathmatics"]
license = "MPL-2.0-no-copyleft-exception"

[dependencies]
